set -g status on
set -g status-position top
set -g status-interval 5

# Status bar
set -gu status-format
set -g  status-style        "bg=black,fg=white"
set -g  status-justify      centre
set -g  status-left-length  40
set -g  status-right-length 40
set -g  status-left         "#{?client_prefix,#[bg=green fg=black] #S ,#[bg=black fg=green] #S }"
set -g  status-right        "#[bg=black fg=blue] #h "

# Tabs/Windows
set -g window-status-activity-style "bg=cyan,fg=black"
set -g window-status-bell-style     "bg=cyan,fg=black"
set -g window-status-last-style     "bg=black,fg=white"
set -g window-status-format         "#[fg=blue] #I:#W "
set -g window-status-current-format " #[bg=black,fg=yellow, bold] #I:#W "
set -g window-status-separator      ""

# Command prompt
set -g message-style         "bg=magenta,fg=black"
set -g message-command-style "bg=black,fg=magenta"

# Pane borders
set -g pane-border-style        "fg=colour8"
set -g pane-active-border-style "fg=colour8"

# Menus
set -g menu-style          "bg=black,fg=white"
set -g menu-selected-style "bg=cyan,fg=black"
set -g menu-border-style   "fg=colour8"

# Popups
set -g popup-style        "bg=black,fg=white"
set -g popup-border-style "fg=colour8"



