###################################################################
# https://docs.helix-editor.com/master/commands.html
###################################################################

theme = "catppuccin_mocha"

[editor]
auto-pairs = false    # do not auto pair symbols
auto-save = true
bufferline = "always"    # show buffer tabs at all times
color-modes = true    # color status line MODE indicator (it's pretty)
cursorline = true    # highlight all rows with cursor
jump-label-alphabet = "asdfjkl;ghxcvbnmqweruioptyz" # home row outward
line-number = "absolute"    # relative absolute
mouse = true
shell = ["zsh", "-c"]
smart-tab.enable = false
soft-wrap.enable = true
true-color = true    # Force the theme to show colors
end-of-line-diagnostics = "hint"
inline-diagnostics.cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = true
git-global = true
# max-depth  = 7

[editor.indent-guides]
render = true
character = "|"

[editor.lsp]
auto-signature-help = false  # Disable automatic popups
display-messages = true    # Show LSP messages in the status line

[editor.statusline]
left = [ "mode", "file-modification-indicator", "file-name" ]
center = ["selections"]
right = ["diagnostics","position",  "file-type", "spinner",
"version-control"]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

###################################################################
# key maps
###################################################################

[keys.normal]
"G" = "goto_file_end"
"H" = "goto_line_start"
"L" = "goto_line_end"
# select line, stay in selection mode
"V" = ["select_mode", "extend_to_line_bounds"]
# OVERRIDE: copy to both internal and external clipboards
"y" = ["yank_main_selection_to_clipboard", "yank"]
# OVERRIDE: Vim like escape
esc = ["collapse_selection", "keep_primary_selection", ":write"]

# Select All
C-a = "@ggvG"
# delete from current line to end of file
C-x = "@VGd"
# replace from os clipboard  (shift-r from helix register)
C-r = ":clipboard-paste-replace"

# buffer move and control [[ ]] \\
[keys.normal."["]
"[" = ":buffer-previous"
[keys.normal."]"]
"]" = ":buffer-next"
[keys.normal."\\"]
"\\" = ":buffer-close"

[keys.normal.space]
n = ":new"
q = ":write-quit-all"
Q = ":quit!"
# expected sort. ":sort" is different
"down" = ":pipe sort"
"up" = ":pipe sort --reverse"

# themes  
[keys.normal.space.t]
a = ":theme autumn_night"
c = ":theme catppuccin_mocha"
e = ":theme ayu_evolve"
g = ":theme gruvbox"
k = ":theme kanagawa"
m = ":theme murmur"
s = ":theme solarized-osaka"
t = ":theme tokyonight"

# config files
[keys.normal.space.space]
c = ":config-open"
l = ":open ~/.config/helix/languages.toml"
r = ":config-reload"
"." = ":open ~/Source/github.com/jeffwindsor/dotfiles"
a = ":open ~/Source/github.com/jeffwindsor/dotfiles/.shellrc"
e = ":open ~/Documents/personal/exocortex"


[keys.insert]
esc = ["collapse_selection", "normal_mode", ":write"] # vim like escape

[keys.select]
"G" = "goto_file_end"
"H" = "goto_line_start"
"L" = "goto_line_end"
"V" = ["select_mode", "extend_to_line_bounds"]
"y" = ["yank_main_selection_to_clipboard", "yank"]
esc = ["collapse_selection", "normal_mode", ":write"]
"~" = "switch_to_uppercase"
"`" = "switch_to_lowercase"

[keys.select.space]
"down" = ":pipe sort"
"up" = ":pipe sort --reverse"
