#!/usr/bin/env sh

configs=(
mbp15-cj
alacritty
alfred
data
fd
git
nvim
starship
topgrade
yabai
youtube-dl 
zsh
)

cd $(dirname "$0")
while (( "$#" )); do
  case "$1" in
    -a|--add)
        ./add "${configs[@]}"
        shift
        ;;

    -r|--remove)
        ./remove "${configs[@]}"
        shift
        ;;
  esac
done
