#!/usr/bin/env zsh
cd $(dirname "$0")

#   /$$$$$$  /$$   /$$ /$$   /$$        /$$$$$$  /$$$$$$$$ /$$$$$$  /$$      /$$
#  /$$__  $$| $$$ | $$| $$  | $$       /$$__  $$|__  $$__//$$__  $$| $$  /$ | $$
# | $$  \__/| $$$$| $$| $$  | $$      | $$  \__/   | $$  | $$  \ $$| $$ /$$$| $$
# | $$ /$$$$| $$ $$ $$| $$  | $$      |  $$$$$$    | $$  | $$  | $$| $$/$$ $$ $$
# | $$|_  $$| $$  $$$$| $$  | $$       \____  $$   | $$  | $$  | $$| $$$$_  $$$$
# | $$  \ $$| $$\  $$$| $$  | $$       /$$  \ $$   | $$  | $$  | $$| $$$/ \  $$$
# |  $$$$$$/| $$ \  $$|  $$$$$$/      |  $$$$$$/   | $$  |  $$$$$$/| $$/   \  $$
#  \______/ |__/  \__/ \______/        \______/    |__/   \______/ |__/     \__/
                                                                              
                                                                              
# use input for root dotfile folder to point to file with list of stow config packages                                                                              
LIST_OF_MACHINE_CONFIGS_FILE="./$1/.local/stows/machine"

# load file lines into array of stow folders
zmodload zsh/mapfile
LIST_OF_MACHINE_CONFIGS_ARRAY=( "${(f)mapfile[$LIST_OF_MACHINE_CONFIGS_FILE]}" )

# unstow then stow each folder 
for folder in "${LIST_OF_MACHINE_CONFIGS_ARRAY[@]}"
do
    # first remove any current stows
    ./remove $folder
    # second add the list of stows
    ./add $folder
done

