#!/usr/bin/env bash
cd $(dirname "$0")

# default source and target if missing
[ -z "$source" ] && source=$(dirname "$0") 
[ -z "$target" ] && target=$HOME

folders=(
    astronvim
    bash
    bat
    data
    dnf
    exa
    fd
    fish
    fzf
    git
    hledger
    linux
    node
    ripgrep
    rust
    starship
    zsh
    ) 

echo "${folders[@]}"

# unstow then stow each folder 
for folder in "${folders[@]}"
do
    if [ ! -z "$folder" ]
    then
        echo -ne "  $folder"
        stow -D -d "$source" -t "$target" "$folder"
        echo -ne "\033[0;34m > cleaned\033[0;30m"

        stow -d "$source" -t "$target" "$folder"
        echo -e "\033[0;32m > added\033[0m"
    fi
done

