#!/usr/bin/env bash

# default source and target if missing
[ -z "$source" ] && source=$(dirname "$0") 
[ -z "$target" ] && target=$HOME

folder="${1}"
if [ ! -z "$folder" ]
then
    echo -e "\033[0;34m $folder (removing) \033[0m"
    stow -D -d $source -t $target $folder
fi
