format = """
[┌ ](blue)$directory$git_branch$git_status$jobs$nix_shell$container
[└ ](blue)$shell$time$character"""

[character]
error_symbol = "[:](red)"
success_symbol = "[:](green)"
vicmd_symbol = "[>](yellow)"

[container]
disabled = false
style = "cyan"

[directory]
fish_style_pwd_dir_length = 1
style = "blue"

[git_branch]
style = "cyan"
symbol = ""

[git_status]
format = '([\[](dimmed yellow)[$all_status$ahead_behind](dimmed yellow)[\]](dimmed yellow)) '

[jobs]
disabled = false
format = '([\[](dimmed blue)[$number](dimmed blue)[\]](dimmed blue))'
number_threshold = 1

[nix_shell]
disabled = false
style = "cyan"

[shell]
disabled = false
style = "dimmed blue"
bash_indicator = "💣"
fish_indicator = "🐟"
zsh_indicator = "🧟"
nu_indicator = "☘️"

[time]
disabled = false
format = '[$time](blue) '
