###################################################################
# https://docs.helix-editor.com/master/commands.html
###################################################################
theme = "tokyonight"

[editor]
auto-pairs = false                                  # do not auto pair symbols
auto-save = true
bufferline = "always"                               # show buffer tabs at all times
color-modes = true                                  # color status line MODE indicator (it's pretty)
cursorline = true                                   # highlight all rows with cursor
jump-label-alphabet = "asdfjkl;ghxcvbnmqweruioptyz" # home row outward
line-number = "absolute"                            # relative absolute
mouse = true
shell = ["zsh", "-c"]
smart-tab.enable = false
soft-wrap.enable = true
# diagnostics after v2.25 
end-of-line-diagnostics = "hint"
inline-diagnostics.cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = true
git-global = true
# max-depth  = 4

[editor.indent-guides]
render = true
character = "|"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "file-modification-indicator",
  "version-control",
]
center = ["position", "selections"]
right = ["diagnostics", "file-encoding", "file-line-ending", "file-type"]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

###################################################################
# key maps
###################################################################

[keys.normal]
"G" = "goto_file_end"
"H" = "goto_line_start"
"L" = "goto_line_end"
"V" = ["select_mode", "extend_to_line_bounds"]
"y" = ["yank_main_selection_to_clipboard", "yank"]
esc = ["collapse_selection", "keep_primary_selection", ":write"]
# Select All
C-a = "@ggvG"
# lazygit in place
C-g = [
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
]
# yazi in place
C-y = [
    ':sh rm -f /tmp/unique-file',
    ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
    ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
    ':open %sh{cat /tmp/unique-file}',
    ':redraw',
]

# replace from clipboard
C-q = ":clipboard-paste-replace"
C-r = ":clipboard-paste-replace"

[keys.normal.space]
q = ":write-quit-all"
Q = ":quit!"
# expected sort. ":sort" is different
"down" = ":pipe sort"
"up" = ":pipe sort --reverse"

# config files (')
[keys.normal."'"]
c = ":config-open"
l = ":open ~/.config/helix/languages.toml"
r = ":config-reload"
"." = ":open ~/Source/github.com/jeffwindsor/dotfiles"
a = ":open ~/Source/github.com/jeffwindsor/dotfiles/.shellrc"
h = ":open ~/Source/github.com/jeffwindsor/nix-darwin-config/Midnight-Air/flake.nix"
w = ":open ~/Source/github.com/jeffwindsor/nix-darwin-config/WKMZTAFD6544/flake.nix"
e = ":open ~/Documents/personal/exocortex"
g = ":open ~/Source/github.com/jeffwindsor/gnome-config"
j = ":open ~/Source/github.com/jeffwindsor"
n = ":open ~/Source/github.com/jeffwindsor/nixos-config"
# s = ":open ~/Source/github.com/jeffwindsor/startpage/index.html"
# v = ":open ~/Source/github.com/jeffwindsor/nvim-config"

# tools(.)
# [keys.normal.space."."]
# f = [":new", ":insert-output lf", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!"]
# d = [":new", ":insert-output lazydocker", ":buffer-close!", ":redraw"]     # lazygit    
# g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]     # lazygit    
# y = [":new", ":insert-output yazi", ":buffer-close!", ":redraw"]     # yazi

# (t)hemes  
[keys.normal.t]
a = ":theme autumn_night"
b = ":theme base16_transparent"
c = ":theme catppuccin_mocha"
d = ":theme default"
e = ":theme ayu_evolve"
g = ":theme gruvbox"
i = ":theme iceberg-dark"
j = ":theme jellybeans"
k = ":theme kanagawa"
l = ":theme ayu_light"
m = ":theme molokai"
n = ":theme nord"
o = ":theme onedark"
p = ":theme papercolor-dark"
s = ":theme sonokai"
t = ":theme tokyonight"
z = ":theme zed_onedark"

[keys.insert]
esc = ["collapse_selection", "normal_mode", ":write"] # vim like escape

[keys.select]
"G" = "goto_file_end"
"H" = "goto_line_start"
"L" = "goto_line_end"
"V" = ["select_mode", "extend_to_line_bounds"]
"y" = ["yank_main_selection_to_clipboard", "yank"]
esc = ["collapse_selection", "normal_mode", ":write"]
