#!/usr/bin/env bash

alias t='exa --color=always --tree'
alias tt='exa --color=always --tree --all'
alias l='exa -lF --color=always --group-directories-first --git'       #alias ll='ls -laLhG'
alias ll='exa -lF --all --color=always --group-directories-first --git'       #alias ll='ls -laLhG'
alias lll='exa -lF --all --color=always --group-directories-first --git-ignore'       #alias ll='ls -laLhG'
