gui:
  screenMode: 'full'

  authorColors:
    '*': '#505050'
    'Jeff Windsor': '#babbf1'
    'Windsor, Jeff': "#99FFE4"

  branchColorPatterns:
    'CJPM-\d+': '#FFBF00'

keybinding:
  universal:
    optionMenu: '~'
    optionMenu-alt1: '?'
    quit-alt1: <esc>
    commitChanges: 'C'

update:
  method: never
