#!/usr/bin/env zsh

install-aur() {
	if paru -Qi $1 &> /dev/null; then
		tput setaf 2
  		echo "==> "$1" is already installed"
      	echo
		tput sgr0
	else
        tput setaf 3
        echo "==> installing package"
        tput sgr0
    	paru -S --noconfirm --needed $1 
    fi
}
