## ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
## ░░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█░░
## ░░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀░░
## ░░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░░░
## ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#
#   STYLES are combinations of:
#     bold, italic, underline, dimmed, inverted, blink, hidden, strikethrough,
#     bg:<color>, fg:<color>, <color>, none,
#   
#     where <color> can be:
#       black, red, green, yellow, blue, magenta, purple, cyan, white, 
#       bright-black, bright-red, bright-green, bright-yellow, bright-blue, 
#       bright-magenta, bright-purple, bright-cyan, bright-white,
#       (ANSI codes: 123), (Hex codes: #aabbcc)
#   
#   reference: https://starship.rs/advanced-config/#style-strings
#

"$schema" = 'https://starship.rs/config-schema.json'

format = """
$shell$directory\
$git_branch$git_state$git_status \
$aws$gleam$golang$haskell$java$kotlin$lua$nodejs$python$rust$scala\
[$time](lowlight)\
$line_break\
$shell$sudo$jobs$character\
"""

#right_format = """[${shell} : ${time} ](lowlight)"""

# command_timeout = 50

palette = "primary"

[palettes.primary]
text1 = "blue"
text2 = "green"
text3 = "yellow"
highlight1 = "bright-blue"
highlight2 = "bright-green"
highlight3 = "bright-yellow"
lowlight = "bright-black"
error = "red"
special = "purple"


[directory]
style = "text1 italic"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
format = "[$symbol$branch](text2 dimmed)"

[git_status]
format = "[[( *$conflicted$untracked$modified$staged$renamed$deleted)](text2)($ahead_behind$stashed)](text2 dimmed)"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = "([ $state($progress_current/$progress_total)](text2 dimmed inverted)) "

[jobs]
format = '[$number](highlight3)'
number_threshold = 1

[docker_context]

[shell]
disabled = false
format = '$indicator'
zsh_indicator = ''
bash_indicator = 'bash '

[time]
disabled = false
format = "$time"

[sudo]
disabled = false
format = "[$symbol](text1)"
symbol = "#"

[character]
success_symbol = "[❯](text1)"
error_symbol = "[❯](error)"
vimcmd_symbol = "[❮](special)"


# NERD FONT (copy)
[aws]
symbol = ""
format = '[${symbol}${version}](text3 dimmed)'

[golang]
symbol = ""
format = '[${symbol}${version}](text3 dimmed)'

[haskell]
symbol = ""
format = '[${symbol}${version}](text3 dimmed)'

[java]
symbol = ""
format = '[${symbol}${version}](text3 dimmed)'

[kotlin]
symbol = ""
format = '[${symbol}${version}](text3 dimmed)'

[lua]
symbol = ""
format = '[${symbol}${version}](text3 dimmed)'

[nodejs]
symbol = ""
format = '[${symbol}${version}](text3 dimmed)'

[python]
symbol = ""
format = '[${symbol}${version}](text3 dimmed)'

[rust]
symbol = "󱘗"
format = '[${symbol}${version}](text3 dimmed)'

[scala]
symbol = ""
format = '[${symbol}${version}](text3 dimmed)'
