# change tmux prefix to [control]+[space]
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Start numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Allows for faster key repetition
set -s escape-time 0

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Highlight active window
set-window-option -g window-status-current-bg red

# allow mouse clicks
set -g mouse on

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g history-limit 10000
set -g renumber-windows on
# don't rename windows automatically
set-option -g allow-rename off

# Vi mode for copy/scroll
setw -g mode-keys vi

# Quick-action menu
bind Space display-menu -T "Quick Actions" \
  "Reload Config"  r "source-file ~/.config/tmux/tmux.conf" \
  "" \
  "Horizontal Split"  h "split-window -v -c '#{pane_current_path}'" \
  "Vertical Split"    v "split-window -h -c '#{pane_current_path}'" \
  "" \
  "Swap Left"           u "swap-pane -L" \
  "Swap Right"         d "swap-pane -R" \
  "Swap Up"           u "swap-pane -U" \
  "Swap Down"         d "swap-pane -D" \
  "" \
  "Kill Pane"         x "kill-pane" \
  "Kill Tab"       X "kill-window"

# ==============================================================================
# Panes

# navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# navigation (no prefix)
bind -n C-h select-pane -L
bind -n C-j select-pane -R
bind -n C-k select-pane -U
bind -n C-l select-pane -D

# swap
bind Left swap-pane -L
bind Right swap-pane -R
bind Up swap-pane -U
bind Down swap-pane -D

# swap (no prefix)
bind -n C-Left swap-pane -L
bind -n C-Right swap-pane -R
bind -n C-Up swap-pane -U
bind -n C-Down swap-pane -D

# resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# new / split
bind \ split-window -h
bind - split-window -v

# close
bind x kill-pane

# fullscreen toggle
bind f resize-pane -Z


# ==============================================================================
# Tabs (Windows)

# close
bind X kill-window

# rename
bind r command-prompt -I "#W" { rename-window "%%" }

# navigation (no prefix)
bind -n C-[ previous-window
bind -n C-] next-window
bind -n C-{ { swap-window -t -1; select-window -t -1 }
bind -n C-} { swap-window -t +1; select-window -t +1 }

# new
bind n new-window






# ==============================================================================
# THEME
# set -g @oasis_flavor "lagoon_dark"
# source-file "~/.config/tmux/oasis/oasis_tmux.conf"
