# change tmux prefix to [control]+[space]
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Start numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Allows for faster key repetition
set -s escape-time 0

# allow mouse clicks
set -g mouse on

# advertise 256-color support to applications inside the session
set -g default-terminal "tmux-256color"

# setting is needed for terminals that advertise 256-color capability in their name (e.g., xterm-256color, gnome-256color, alacritty, kitty, wezterm, iTerm2, etc.)
set -ga terminal-overrides ",*256col*:Tc"

# scrollback buffer size
set -g history-limit 10000

# automatically renumbers windows sequentially whenever a window is closed
set -g renumber-windows on

# prevent tmux from automatically renaming windows
set-option -g allow-rename off
set-option -g automatic-rename off
set-option -g allow-rename off
# start all new non named windows to "."
set-option -g window-status-format "."
set-option -g window-status-current-format "."

# Vi mode for copy/scroll
setw -g mode-keys vi

# status bar to top
set -g status-position top

# Quick-action menu
bind Space display-menu -T "Quick Actions" \
  "Reload Config"  r "source-file ~/.config/tmux/tmux.conf" \
  "" \
  "Horizontal Split"  h "split-window -v -c '#{pane_current_path}'" \
  "Vertical Split"    v "split-window -h -c '#{pane_current_path}'" \

# ==============================================================================
# Panes

# navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# navigation (no prefix)
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# swap
bind-key -T prefix Left  swap-pane -t '{left-of}'
bind-key -T prefix Right swap-pane -t '{right-of}'
bind-key -T prefix Up    swap-pane -t '{up-of}'
bind-key -T prefix Down  swap-pane -t '{down-of}'

# swap (no prefix)
bind-key -n C-Left  swap-pane -t '{left-of}'
bind-key -n C-Right swap-pane -t '{right-of}'
bind-key -n C-Up    swap-pane -t '{up-of}'
bind-key -n C-Down  swap-pane -t '{down-of}'

# resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# new / split
bind \\ split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

# close
bind x kill-pane

# fullscreen toggle
bind f resize-pane -Z

# rename pane
bind r command-prompt -I "#{pane_title}" { select-pane -T "%%" }


# ==============================================================================
# Tabs (Windows)

# close
bind X kill-window

# rename
bind R command-prompt -I "#W" { rename-window "%%" }

# navigation (no prefix)
bind -n C-< previous-window
bind -n C-> next-window
# bind -n C-{ { swap-window -t -1; select-window -t -1 }
# bind -n C-} { swap-window -t +1; select-window -t +1 }

# new
bind n command-prompt { new-window -n "%%" }


# ==============================================================================

# plugin manager requires the folowing to work:
#   > git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
#   > run '~/.tmux/plugins/tpm/tpm'
#
# prefix + I        =>  fetch plugins
# prefix + u        =>  upadate plugins
# prefix + alt + u  =>  uninstall plugin
#
set -g @plugin 'tmux-plugins/tpm'

# set -g @plugin 'tmux-plugins/tmux-sensible'

# theme
set -g @tmux-gruvbox 'dark256'
set -g @tmux-gruvbox-right-status-x ' '  # was date
set -g @tmux-gruvbox-right-status-y ' ' # was time
set -g @plugin 'egel/tmux-gruvbox'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


