#!/usr/bin/env zsh
alias sdk-start="source $HOME/.sdkman/bin/sdkman-init.sh"
alias acd="aws-cloudfront-describe"
alias acd="aws-cloudfront-describe-status"
alias dbstart="nohup VBoxHeadless --startvm 'Oracle11g32' &> /dev/null &"
alias dbstop="VBoxManage controlvm Oracle11g32 poweroff"
alias java11='sdk use java 11.0.12.7.2-amzn'
alias java17='sdk use java 17.0.1.12.1-amzn'
alias java8='sdk use java 8.302.08.1-amzn'
alias qb='java8 && mvn clean install -T 1C -Ddelta.skip=true -Dcleanup.skip=true -Dqunit.numThreads=8 -DskipTests -Dtablespaces.skip=true -Dgulp.task=min && java11'
alias qqb='java8 && mvn install -T 1C -Ddelta.skip=true -Dcleanup.skip=true -Dqunit.numThreads=8 -DskipTests -Dtablespaces.skip=true -Dgulp.task=min && java11'
alias shopcart='sqlplus -L jwindsor@shopcart'
alias shuttle-init="$HOME/.local/scripts/cj/shuttle-init"
alias t1='sqlplus -L cj@tcjoweb1'
alias test-schemas='java -jar ./target/schemas-main-SNAPSHOT.one-jar.jar locator=T5 tnsnames=/USers/jwindsor/.local/cjdev/ci/tns-admin/tnsnames.ora'
alias tns='v ~/.local/cjdev/ci/tns-admin/tnsnames.ora'
alias uber='cd Library/Application\ Support/Übersicht/widgets/'

alias lab='cd $SRC/gitlab.cj.dev'
alias labs="exec-on-git-repos cd $SRC/gitlab.cj.dev"
alias emp='cd $SRC/gitlab.cj.dev/empire'
alias emps="exec-on-git-repos cd $SRC/gitlab.cj.dev/empire"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
