#!/usr/bin/env zsh

exec-on-file () {
    local result=`fd . "$2" -t f -H --ignore-file $XDG_CONFIG_HOME/fdignore | fzf`
    [ ! -z "$result" ] && $1 "$result"
}

stack-new(){ stack new $1 && cd $1 && stack setup && stack build; }

search-alias-functions(){
    echo '\e[1;34mNames\e[0m'
    print -l ${(ok)functions} | grep $1;
    echo '\e[1;34mAliases\e[0m'
    alias | grep $1;
}

cs () {
    cd "$@" && ls
}

function ping-time() {
    ping -c 4 "$1" | tail -1 | awk '{print $4}' | cut -d '/' -f 2
}


alias .....='cd ../../../../'
alias ....='cd ../../../'
alias ...='cd ../../'
alias ..='cd ..'
alias cat='bat -p'
alias config='cd $XDG_CONFIG_HOME'
alias configs='nvim -c ":Files $XDG_CONFIG_HOME"'
alias d='dirs -v | head -10'
alias dot='cd $HOME/.dotfiles'
alias dots='nvim -c ":Files $HOME/.dotfiles"'
alias grep='rg'
alias k='clear'
alias kk='clear && reset'
alias saf='search-alias-functions'
alias setup='cd $HOME/.setups'
alias setups='nvim -c ":Files $HOME/.setups"'
alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"
