#!/usr/bin/env zsh

exec-on-git-repos () {
    local result=`git-find-dirs $2 | cut -d '/' -f5- | fzf --preview="tree -L 1 {}" --bind="space:toggle-preview" --preview-window=:hidden --reverse --height 40% | awk -v path="$2/" '{print path $0}'`
    [ ! -z "$result" ] && $1 $result
}
exec-on-file () {
    local result=`fd . "$2" -t f -H --ignore-file $XDG_CONFIG_HOME/fdignore | fzf`
    [ ! -z "$result" ] && $1 "$result"
}
stack-new(){ stack new $1 && cd $1 && stack setup && stack build; }
search-alias-functions(){
    echo '\e[1;34mNames\e[0m'
    print -l ${(ok)functions} | grep $1;
    echo '\e[1;34mAliases\e[0m'
    alias | grep $1;
}

alias .....='cd ../../../../'
alias ....='cd ../../../'
alias ...='cd ../../'
alias ..='cd ..'
alias cat='bat -p'
alias config='cd $XDG_CONFIG_HOME'
alias configs='nvim -c ":Files $XDG_CONFIG_HOME"'
alias d='dirs -v | head -10'
alias doom="$HOME/.emacs.d/bin/doom"
alias dot='cd $HOME/.dotfiles'
alias dots='nvim -c ":Files $HOME/.dotfiles"'
alias f='vifm'
alias grep='rg'
alias k='clear'
alias kk='clear && reset'
alias repo='cd $HOME/src'
alias repos='exec-on-git-repos cd $SRC'
alias saf='search-alias-functions'
alias src='cd $HOME/src'
alias srcs="exec-on-git-repos cd $SRC"
alias theme="$HOME/.local/scripts/alacritty/change_theme"
alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"

alias lx='nnn -de'

alias tree='exa --all --color=always --tree'
alias l='exa -lF --color=always --group-directories-first'       #alias ll='ls -laLhG'
alias ll='exa -lF --all --color=always --group-directories-first'       #alias ll='ls -laLhG'
alias lll='exa -lF --all --color=always --group-directories-first --git-ignore'       #alias ll='ls -laLhG'
