#!/usr/bin/env bash

################################################################################
# POP-OS KEYBINDINGS
################################################################################
set -e
cd "$(dirname "${0}")"

echo-color(){ printf "\033[0;32m==> $1 \033[0m \n"; }
echo-color "POP SHELL KEYBINDINGS"
echo-color "Applications"
dconf write '/org/gnome/shell/extensions/pop-shell/activate-launcher' "['<Super>space']"
dconf write '/org/gnome/shell/extensions/pop-shell/tile-enter' "@as ['<Super>m']"

