#!/usr/bin/env sh
# 
#   /$$$$$$                                          /$$                          
#  /$$__  $$                                        | $$                          
# | $$  \__/  /$$$$$$   /$$$$$$   /$$$$$$$  /$$$$$$ | $$$$$$$   /$$$$$$   /$$$$$$ 
# |  $$$$$$  /$$__  $$ |____  $$ /$$_____/ /$$__  $$| $$__  $$ |____  $$ /$$__  $$
#  \____  $$| $$  \ $$  /$$$$$$$| $$      | $$$$$$$$| $$  \ $$  /$$$$$$$| $$  \__/
#  /$$  \ $$| $$  | $$ /$$__  $$| $$      | $$_____/| $$  | $$ /$$__  $$| $$      
# |  $$$$$$/| $$$$$$$/|  $$$$$$$|  $$$$$$$|  $$$$$$$| $$$$$$$/|  $$$$$$$| $$      
#  \______/ | $$____/  \_______/ \_______/ \_______/|_______/  \_______/|__/      
#           | $$                                                                  
#           | $$                                                                  
#           |__/                                                                  
# 
spacebar -m config position             top
spacebar -m config height               26
spacebar -m config title                on
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15
spacebar -m config text_font            "JetBrains Mono:Regular:13.0"
spacebar -m config icon_font            "Font Awesome 5 Free:Solid:13.0"
spacebar -m config background_color     0xFF2b202a  # cyberpunk
spacebar -m config foreground_color     0xFF00c4ff  # A5ff00c4  # cyberpunk

spacebar -m config display_separator    off

spacebar -m config space_icon           "."
spacebar -m config space_icon_color     0xff458588
spacebar -m config space_icon_strip     1 2 3 4 5 6 7 8 9

spacebar -m config clock                on
spacebar -m config clock_icon           " "
spacebar -m config clock_icon_color     0xffa8a8a8
spacebar -m config clock_format         "%A %B, %d %I:%M%p"

spacebar -m config power_icon_strip     "🔋" "⚡"
#spacebar -m config power_icon_color     0xffff00c4
#spacebar -m config battery_icon_color   0xffd75f5f

spacebar -m config dnd_icon             "*"
#spacebar -m config dnd_icon_color       0xffa8a8a8

spacebar -m config left_shell           off
spacebar -m config center_shell         off
spacebar -m config right_shell          off

# leave room for spacebar at top
yabai -m config external_bar all:26:0

