#!/bin/sh

export LEDGER_DIR="$SRC/github.com/jeffwindsor/hledger-data"
export LEDGER_IMPORTS_DIR="$LEDGER_DIR/imports"
export LEDGER_FILE="$LEDGER_DIR/personal-finances.journal"

alias hl="hledger"
alias hld="cd $LEDGER_DIR"
alias hlup="git -C $LEDGER_FILE commit -a -m 'manual save' && git -C $LEDGER_FILE push"
