# shells
brew "bash"
brew "zsh"

# clis
brew "bat"
brew "clifm"
brew "fd"
brew "fzf"
brew "git"
brew "lazygit"
brew "lsd"
brew "mise"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "stow"
brew "television"
tap "tinted-theming/tinted"
brew "tinted-theming/tinted/tinty"
brew "tree-sitter-cli"


# guis
tap "nikitabobko/tap"
cask "aerospace"
cask "brave-browser"
cask "font-jetbrains-mono-nerd-font"
cask "raycast"
cask "bluesnooze"
cask "kitty"

# personal
cask "balenaetcher"
cask "bambu-studio"
cask "iina"
cask "spotify"
cask "transmission"
