vim.opt.autoindent	    = true
vim.opt.background	    = 'dark'
vim.opt.clipboard       = 'unnamedplus' 
vim.opt.cursorline	    = true            
vim.opt.encoding        = 'UTF-8'
vim.opt.expandtab       = true			    -- spaces over tabs
vim.opt.hidden          = true			    -- allow background buffers 
vim.opt.hlsearch        = true			    -- highlight found searches
vim.opt.ignorecase	    = true        
vim.opt.inccommand	    = 'split'		    -- get preview of replacements
vim.opt.incsearch 	    = true       		-- show match while typing
vim.opt.number          = true
vim.opt.relativenumber  = true			    -- hybrid number scheme
vim.opt.ruler           = true
vim.opt.shiftwidth	    = 2
vim.opt.smartindent     = true
vim.opt.smarttab        = true
vim.opt.softtabstop	    = 2
vim.opt.spell           = true
vim.opt.spelllang       = 'en_us'
vim.opt.splitbelow	    = true
vim.opt.splitright	    = true
vim.opt.tabstop		    = 2
vim.opt.termguicolors	= true
vim.opt.wrap	        = false
