gui:
  authorColors:
    'Jeff Windsor': 'blue'
    '*': 'cyan'
git:
  paging:
    color: always
    pager: "delta --dark --paging=never --line-numbers"

keybinding:
  universal:
    optionMenu: '~' # show help menu
    optionMenu-alt1: '?' # show help menu
