#!/usr/bin/env zsh

git-to-main() { git branch -m master main && git push -u origin main; }
git-commit(){ git commit -m ${1:-'Refactor'}; }
git-log-graph(){ git log --graph --pretty=format:${GIT_LOG_PRETTY_FORMAT} --abbrev-commit --max-count=${1:-10}; }
git-find-dirs () { find $1 -type d \( -exec test -d "{}/.git" -a "{}" != "." \; -print -prune -o -name .git -prune \); }

alias ga='git add'
alias gaa='git add --all'
alias gb='git branch -v'
alias gc='git clone'
alias gcm='git-commit'
alias gco='git checkout'
alias gd='git diff --ignore-space-at-eol -b -w --ignore-blank-lines'
alias gh='git-log-graph'
alias gl='git log'
alias gph='git push'
alias gpl='git pull'
alias gr='git remote -vv'
alias gs='git status -sb --ignore-submodules'
alias gsync='git checkout master && git pull --rebase && git checkout - && git rebase master'
