#!/bin/bash

alias up='sudo dnf -y upgrade && flatpak -y upgrade'

alias dup='sudo dnf upgrade'
alias din='sudo dnf install'
alias dar='sudo dnf autoremove'
alias dif='sudo dnf info'
alias dch='dnf check-upgrade'
alias dck='dnf check-upgrade'
alias dls='dnf history --userinstalled'
