[metadata]
name = "dotfiles"
description = "A channel to select from your user's dotfiles"
requirements = ["fd", "bat"]

[source]
command = "fd -t f . $DOTFILES"


[preview]
command = "bat -n --color=always '{}'"
