[metadata]
name = "tnsnames"
description = "Browse and preview tnsnames in the ~/tnsnames.ora file"
requirements = ["awk", "awk"]

[source]
command = '''awk -F'=' '/^[A-Za-z0-9_]+[[:space:]]*=/ {gsub(/[[:space:]]/, "", $1); print $1}' ~/tnsnames.ora'''

[preview]
command = '''awk -v tns="{}" '$0 ~ "^" tns "[[:space:]]*=" {flag=1} flag && /^[A-Za-z0-9_]+[[:space:]]*=/ && $0 !~ "^" tns "[[:space:]]*=" {flag=0} flag' ~/tnsnames.ora'''
