#!/usr/bin/env bash

mkdir shuttle
cd shuttle

cat << EOF >> build.sh
#!/bin/bash
set -o errexit
set -o noglob
set -o nounset
set -o pipefail

cd "\$(dirname "\${0}")"


# call build.sh in root directory
../build.sh

EOF

chmod +x build.sh

cat << EOF >> deploy.sh
#!/bin/bash
set -o errexit
set -o noglob
set -o nounset
set -o pipefail

cd "\$(dirname "\${0}")"

echo "Deploying Environment $SHUTTLE_ENV_NAME"

if test $SHUTTLE_ENV_NAME = "CJ Empire Developers"
then
    ../deploy.sh 

elif test $SHUTTLE_ENV_NAME = "CJ Finance Product"
then
    ../deploy.sh 

else
    echo "==> Unknown Deploy Environment"
    exit 1
fi

EOF

chmod +x deploy.sh

cat << EOF >> shuttle.json
{
  "environments": [
    {
      "name": "CJ Empire Developers",
      "account": "845290112482"
    },
    {
      "name": "CJ Finance Product",
      "account": "900394040587"
    }
  ],
  ],
  "artifactFiles": [
  ]
}
EOF
    
