#!/usr/bin/env bash
set -e
cd "$(dirname "${0}")"

function echo-color(){ 
    printf "\033[0;32m==> $1 \033[0m \n" 
}
echo-color "Gnome KEYBINDINGS"

echo-color "Applications"
dconf write '/org/gnome/settings-daemon/plugins/media-keys/terminal' "['<Super>Return']"
dconf write '/org/gnome/settings-daemon/plugins/media-keys/www' "['<Super><Alt>Return']"
dconf write '/org/gnome/settings-daemon/plugins/media-keys/home' "['<Super><Alt><Primary>Return']"
dconf write '/org/gnome/settings-daemon/plugins/media-keys/control-center' "['<Super>comma']"
dconf write '/org/gnome/settings-daemon/plugins/media-keys/email' '@as []'

echo-color "System"
dconf write "/org/gnome/shell/keybindings/close" "['<Super>q']"
dconf write "/org/gnome/shell/keybindings/toggle-message-tray" "['<Super>n']"

dconf write "/org/gnome/desktop/wm/keybindings/panel-run-dialog" "['<Super><Alt>space']"
dconf write "/org/gnome/shell/keybindings/toggle-application-view" "['<Super>space']"
dconf write "/org/gnome/desktop/wm/keybindings/panel-main-menu" "['<Alt>Up']"

echo-color "Windows"
dconf write "/org/gnome/mutter/dynamic-workspaces" "false"
dconf write "/org/gnome/desktop/wm/preferences/num-workspaces" "9"

dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1" "['<Super>1']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2" "['<Super>2']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3" "['<Super>3']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4" "['<Super>4']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5" "['<Super>5']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6" "['<Super>6']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7" "['<Super>7']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8" "['<Super>8']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9" "['<Super>9']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-last" "@as []"

dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-1" "['<Super><Alt>1']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-2" "['<Super><Alt>2']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-3" "['<Super><Alt>3']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-4" "['<Super><Alt>4']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-4" "['<Super><Alt>4']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-5" "['<Super><Alt>5']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-6" "['<Super><Alt>6']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-7" "['<Super><Alt>7']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-8" "['<Super><Alt>8']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-9" "['<Super><Alt>9']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-up" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-down" "@as []"

dconf write "/org/gnome/desktop/wm/keybindings/move-to-monitor-left" "['<Super><Alt><Shift>Left', '<Super><Alt><Shift>h']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-monitor-right" "['<Super><Alt><Shift>Right', '<Super><Alt><Shift>l']"

dconf write "/org/gnome/desktop/wm/keybindings/switch-applications-backward" "['<Shift><Super>Tab']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-applications" "['<Super>Tab']"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-applications-backward" "['<Shift><Alt><Super>Tab']"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-applications" "['<Alt><Super>Tab']"

echo-color "Create Custom Keybinding entries"

MEDIA_KEYS='/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings' 
addCustom(){
    dconf write "$MEDIA_KEYS/custom$1/binding" "$2"
    dconf write "$MEDIA_KEYS/custom$1/command" "$3"
    dconf write "$MEDIA_KEYS/custom$1/name" "$4"
}

# create custom key entries
dconf write "$MEDIA_KEYS" "['$MEDIA_KEYS/custom0/','$MEDIA_KEYS/custom1/']"

addCustom "0" "['<Super>Return']" "'alacritty'" "'Launch Terminal'"
addCustom "1" "'<Super>x'" "'/usr/local/bin/arcolinux-logout'" "'Launch Logout Tool'"
