#!/usr/bin/env bash

function git-commit
    git commit -m ${1:-'Refactor'}
end

function git-add-commit-push 
    git add --all
    git commit -m ${1:-'Refactor'} 
    git push
end

function git-log-graph
    git log --graph --pretty=format:${GIT_LOG_PRETTY_FORMAT} --abbrev-commit --max-count=${1:-10}
end

function git-find-dirs 
    find $1 -type d \( -exec test -d "{}/.git" -a "{}" != "." \; -print -prune -o -name .git -prune \)
end

function exec-on-git-repos 
    local result=`git-find-dirs $2 | cut -d '/' -f5- | fzf --preview="tree -L 1 {}" --bind="space:toggle-preview" --preview-window=:hidden --reverse --height 40% | awk -v path="$2/" '{print path $0}'`
    [ ! -z "$result" ] && $1 $result
end

function gphs 
    for i in **/.git
        echo $i
        git -C $i/.. push
    end
end

function gpls 
    for i in **/.git
        echo $i
        git -C $i/.. pull
    end
end
