#!/usr/bin/env zsh
# Generated function script: git-goto-repo
# Source: ~/.config/zsh/user-modules/

git-goto-repo() {
  local repo=$(tv my-git-repos)
  if [[ -n "$repo" ]]; then 
    cd "$repo"
    clear
    lsd -1A
  fi
}

git-goto-repo "$@"
