#!/usr/bin/env sh

# 
#  /$$     /$$        /$$                 /$$
# |  $$   /$$/       | $$                |__/
#  \  $$ /$$//$$$$$$ | $$$$$$$   /$$$$$$  /$$
#   \  $$$$/|____  $$| $$__  $$ |____  $$| $$
#    \  $$/  /$$$$$$$| $$  \ $$  /$$$$$$$| $$
#     | $$  /$$__  $$| $$  | $$ /$$__  $$| $$
#     | $$ |  $$$$$$$| $$$$$$$/|  $$$$$$$| $$
#     |__/  \_______/|_______/  \_______/|__/
#                                            

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xffb3deef
yabai -m config normal_window_border_color   0xff293b44
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  08
yabai -m config bottom_padding               08
yabai -m config left_padding                 08
yabai -m config right_padding                08
yabai -m config window_gap                   08

# space labels
#yabai -m space 1 --label I
#yabai -m space 2 --label II
#yabai -m space 3 --label III
#yabai -m space 4 --label IV
#yabai -m space 5 --label V
#yabai -m space 6 --label VI
#yabai -m space 7 --label VII
#yabai -m space 8 --label VIII
#yabai -m space 9 --label IX
