#!/usr/bin/env bash

export HISTCONTROL=ignoreboth
export LESSHISTFILE="-"
#export MANPAGER="sh -c 'col -bx | bat -l man -p'" # use bat as man pager
export TERM='xterm-256color'
export ZSH_PLUGINS='/usr/share'
