#!/usr/bin/env bash
################################################################################
# ARCH / ARCO
################################################################################
cd "$(dirname "${0}")"

header(){
    tput setaf 3
    echo "==> " $@
    tput sgr0
}

install() {
	if pacman -Qi $1 &> /dev/null; then
		tput setaf 2
  		echo "==> "$1" is already installed"
      	echo
		tput sgr0
	else
    	header "==> installing package "  $1
    	sudo pacman -S --noconfirm --needed $1 
    fi
}

install-aur() {
	if paru -Qi $1 &> /dev/null; then
		tput setaf 2
  		echo "==> "$1" is already installed"
      	echo
		tput sgr0
	else
    	header "==> installing package "  $1
    	paru -S --noconfirm --needed $1 
    fi
}

clone-if-missing(){
    [[ ! -d $2 ]] && git clone https://github.com/${1}/${2}.git $2
}
################################################################################
## SSH KEY 
if [[ "$(read -e -p 'Add SSH key? [y/N]> '; echo $REPLY)" == [Yy]* ]]
then
    #echo "==> SSH"
    ssh-keygen -t ed25519 -C "jeff.windsor@gmail.com"
    eval $(ssh-agent)
    ssh-add ~/.ssh/id_ed25519
fi

################################################################################
header "common directories"
mkdir -p ${HOME}/src/github.com

################################################################################
header "System: Use Fastest 5 Mirrors in US and Canada" 
sudo reflector --verbose --country 'United States, Canada' -l 5 -p http --sort rate --save /etc/pacman.d/mirrorlist

header "System: Update Packages" 
sudo pacman -Syu
install paru

header "System: Bluetooth"
install bluez bluez-utils

header "Desktop Environment: gnome"
install gnome
install gnome-extra
install gnome-shell-extension-pop-shell-git 
install gnome-shell-extension-sound-output-device-chooser
install xdg-utils

header "Desktop: applications"
install firefox
install brave-browser

header "Terminal: packages"
install alacritty
install bat
install exa
install fd
install fzf
install keychain
install ripgrep
install stow
install tldr
install starship
install zsh 
install zsh-autosuggestions 
install zsh-completions
install zsh-history-substring-search
install zsh-syntax-highlighting

header "Editors: neovim"
install neovim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim --headless +PlugInstall +qall


header "Programming Languages: Rust"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

header "Programming Languages: Go Lang"
install go

header "System: Set ZSH as DEFAULT"
chsh -s "$(which zsh)"

################################################################################
header "Manual steps"

# add ssh key to git hub
xdg-open https://github.com/settings/keys/

# add mega syns
xdg-open https://mega.nz/sync/

# add lastpass
xdg-open https://lastpass.com/

# MacbookPro Retina 15 Wifi: broadcom 14E4:43A0
#   https://unix.stackexchange.com/questions/175810/how-to-install-broadcom-bcm4360-on-debian-on-macbook-pro
#install broadcom-sta-dkms
#sudo modprobe -r b44 b43 b43legacy ssb brcmsmac
#sudo modprobe wl

# Laptop Power Management
#sysdl='/etc/systemd/logind.conf'
#cat $sysdl \
#    | sed -r 's/\#?HandleLidSwitchExternalPower=.*/HandleLidSwitchExternalPower=ignore/g' \
#    | sed -r 's/\#?HandleLidSwitch=.*/HandleLidSwitch=poweroff/g' \
#    | sudo tee $sysdl

