#!/usr/bin/env bash
################################################################################
# ARCH / ARCO
################################################################################
cd "$(dirname "${0}")"

header(){
    tput setaf 3
    echo "==> " $@
    tput sgr0
}

install() {
	if pacman -Qi $1 &> /dev/null; then
		tput setaf 2
  		echo "==> "$1" is already installed"
      	echo
		tput sgr0
	else
    	header "==> installing package "  $1
    	sudo pacman -S --noconfirm --needed $1 
    fi
}

clone-if-missing(){
    [[ ! -d $2 ]] && git clone https://github.com/${1}/${2}.git $2
}
################################################################################
## SSH KEY 
read -p "Add SSH Key? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    #echo "==> SSH"
    ssh-keygen -t ed25519 -C "jeff.windsor@gmail.com"
    eval $(ssh-agent)
    ssh-add ~/.ssh/id_ed25519
fi

header "Use Fastest 5 Mirrors" 
sudo reflector --verbose --country 'United States, Canada' -l 5 -p http --sort rate --save /etc/pacman.d/mirrorlist

header "Update Packages" 
sudo pacman -Syu

header "common directories"
mkdir -p ${HOME}/src/hub

header "packages"
install alacritty
install bat
install exa
install fd
install fzf

install neovim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim --headless +PlugInstall +qall

install ripgrep

#rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

install starship
install stow
install tldr

install zsh 
install zsh-autosuggestions 
install zsh-completions
install zsh-history-substring-search
install zsh-syntax-highlighting
# ZSH as DEFAULT shell
chsh -s "$(which zsh)"

paru -S nerd-fonts-jetbrains-mono
################################################################################
header "Manual steps"
xdg-open https://github.com/settings/keys
xdg-open https://mega.nz/sync

# MacbookPro Retina 15 Wifi: broadcom 14E4:43A0
#   https://unix.stackexchange.com/questions/175810/how-to-install-broadcom-bcm4360-on-debian-on-macbook-pro
#install broadcom-sta-dkms
#sudo modprobe -r b44 b43 b43legacy ssb brcmsmac
#sudo modprobe wl

# Laptop Power Management
#sysdl='/etc/systemd/logind.conf'
#cat $sysdl \
#    | sed -r 's/\#?HandleLidSwitchExternalPower=.*/HandleLidSwitchExternalPower=ignore/g' \
#    | sed -r 's/\#?HandleLidSwitch=.*/HandleLidSwitch=poweroff/g' \
#    | sudo tee $sysdl

