# docs: https://alacritty.org/config-alacritty.html

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12.0

[general]
live_config_reload = true
# color_scheme import is replaced by shell function
import=["~/.config/alacritty/themes/tender.toml"]

# [keyboard]
# bindings = [{ <key>, <mods>, <mode>, <command> | <chars> | <action> },]

[window]
decorations = "None"
padding = { x = 8, y = 8 }
opacity = 0.94
