import=['/home/mid/.config/alacritty/themes/tender.toml']

[window]
padding = { x = 8, y = 8 }
opacity = 0.98

[cursor]
style = "Block"

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 14.0
