#
# docs: https://alacritty.org/config-alacritty.html
#

# color_scheme import is replaced by shell function
import = ['/Users/jeffwindsor/.config/alacritty/themes/tender.toml']

#[cursor]
#style = "Block"  #default value

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12.0

# [keyboard]
# bindings = [{ <key>, <mods>, <mode>, <command> | <chars> | <action> },]

[window]
decorations = "None"
padding = { x = 8, y = 8 }
opacity = 0.94
