#!/usr/bin/env zsh

source $ZSH_PLUGINS/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH_PLUGINS/zsh-history-substring-search/zsh-history-substring-search.zsh
source $ZSH_PLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

brews() {
    local result=$(brew formulae | fzf -m --preview="brew info {}" --preview-window=:hidden --bind=space:toggle-preview)
    [ ! -z "$result" ] && brew install "$result"
}
casks() {
    local result=$(brew search --casks | fzf -m --preview="brew cask info {}" --preview-window=:hidden --bind=space:toggle-preview)
    [ ! -z "$result" ] && brew cask install "$result"
}
sshkey(){ ssh-keygen -t ed25519 -C $1 -f $2; }
sshadd(){ eval "$(ssh-agent -s)" && ssh-add -K ~/.ssh/${1}; }
sha1-check()  { shasum -a 1 -c "$1.sha1"; }
sha256-check(){ shasum -a 256 -c "$1.sha256"; }
sha512-check(){ shasum -a 512 -c "$1.sha512"; }
md5-check()  { md5 -r "$1" | diff "$1.md5" -; }
alias aws1="alias aws='/usr/local/opt/awscli@1/bin/aws'"
alias aws2="unalias aws"
alias bc="brew cask"
alias bi="brew info"
alias bl="brew list && brew cask list && mas list"
alias bs="brew search"
alias bt="brew leaves | xargs brew deps --installed --for-each | sed \"s/^.*:/$(tput setaf 4)&$(tput sgr0)/\""
alias bundle_name="osascript -e 'id of app"
alias caskroom="cd /usr/local/Caskroom && l"
alias cellar="cd /usr/local/Cellar && l"
alias m5c="md5-check"
alias mf="mas info"
alias mi="mas install"
alias ml="mas list"
alias mr="mas uninstall"
alias ms="mas search"
alias mup="mas upgrade"
alias s1="shasum -a 1"
alias s1c="sha1-check"
alias s2="shasum -a 256"
alias s2c="sha256-check"
alias s5="shasum -a 512"
alias s5c="sha512-check"
alias remove-ds-store="find . -name '.DS_Store' -type f -delete"
