#!/bin/bash
#source https://github.com/x70b1/polybar-scripts
#source https://github.com/polybar/polybar-scripts

if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
    updates_arch=0
fi
if ! updates_aur=$(checkupdates-aur 2> /dev/null | wc -l ); then
    updates_aur=0
fi

#   
if [ $updates_arch -gt 0 ] || [ $updates_aur -gt 0 ]
then
    echo "%{B#C2D94C}  %{B-}"
else
    echo ""
fi
