#!/usr/bin/env bash

gch() { git clone git@github.com:$1 $HOME/Source/github.com/$1; }
git-to-main() { git branch -m master main && git push -u origin main; }
git-commit(){ git commit -m ${1:-'Refactor'}; }
git-log-graph(){ git log --graph --pretty=format:${GIT_LOG_PRETTY_FORMAT} --abbrev-commit --max-count=${1:-10}; }
git-find-dirs () { find $1 -type d \( -exec test -d "{}/.git" -a "{}" != "." \; -print -prune -o -name .git -prune \); }
exec-on-git-repos () {
    local result=`git-find-dirs $2 | cut -d '/' -f5- | fzf --preview="tree -L 1 {}" --bind="space:toggle-preview" --preview-window=:hidden --reverse --height 40% | awk -v path="$2/" '{print path $0}'`
    [ ! -z "$result" ] && $1 $result
}

alias ga='git add'
alias gaa='git add --all'
alias gb='git branch -v'
alias gc='git clone'
alias gcm='git-commit'
alias gco='git checkout'
alias gd='git diff --ignore-space-at-eol -b -w --ignore-blank-lines'
alias gh='git-log-graph'
alias gl='git log'
alias gph='git push'
alias gphs='for i in **/.git; do ( echo $i; cd $i/..; git push; ); done'
alias gpl='git pull'
alias gpls='for i in **/.git; do ( echo $i; cd $i/..; git pull; ); done'
alias gr='git remote -vv'
alias gs='git status -sb --ignore-submodules'
alias gsync='git checkout master && git pull --rebase && git checkout - && git rebase master'
alias src='cd $HOME/Source'
alias srcs="exec-on-git-repos cd $SRC"
