#!/usr/bin/env bash

alias src="cd $SRC"
alias srcs="exec-on-git-repos cd $SRC"

alias hub="cd $SRC/github.com"
alias hubs="exec-on-git-repos cd $SRC/github.com/"
alias jeff="cd $SRC/github.com/jeffwindsor/"

alias dot="cd $DOTFILES"
alias in="cd $INSTALLS"

alias git-to-main="git branch -m master main && git push -u origin main"

alias gup="git-add-commit-push"
alias ga="git add"
alias gaa="git add --all"
alias gb="git branch -v"
alias gc="git clone"
alias gcm="git-commit"
alias gco="git checkout"
alias gd="git diff --ignore-space-at-eol -b -w --ignore-blank-lines"
alias gh="git-log-graph"
alias gl="git log"
alias gph="git push"
alias gpl="git pull"
alias gr="git remote -vv"
alias gs="git status -sb --ignore-submodules"

# sync with remote master
alias gsync="git checkout master && git pull --rebase && git checkout - && git rebase master"

# lazygit
alias lg=lazygit

