#!/usr/bin/env zsh

alias v='nvim'
alias vv='nvim -O'

alias configs='nvim -c "Telescope find_files cwd=$HOME/$XDG_CONFIG_HOME hidden=true"'
alias dots='nvim -c "Telescope find_files cwd=$HOME/.dotfiles hidden=true"'
alias ins='nvim -c "Telescope find_files cwd=$HOME/.installs"'
