# === font ===
bold_font        auto
bold_italic_font auto
font_family      family="JetBrainsMono Nerd Font Mono"
font_size        16.0
italic_font      auto

# === visual settings ===
allow_remote_control                no
confirm_os_window_close             0
enable_audio_bell                   no
enabled_layouts                     tall,horizontal,vertical,stack
hide_window_decorations             yes
macos_option_as_alt                 yes
macos_quit_when_last_window_closed  yes
macos_show_window_title             no
shell_integration                   no_title
tab_bar_edge                        top
tab_bar_style                       slant
tab_bar_min_tabs                    1   
window_padding_width                4

# === keybindings ===
# new windows use current directory
map cmd+enter new_window_with_cwd

# layouts
unmap ctrl+shift+f
map ctrl+shift+f toggle_layout stack

# new tab with rename
map cmd+t combine : new_tab : set_tab_title " "

# tab navigation - additional bindings
map ctrl+] next_tab
map ctrl+[ previous_tab

# window navigation
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# tinted theme sets the values in this file to selected theme
include ./tinted-theming.conf
