# === font ===
bold_font        auto
bold_italic_font auto
font_family      family="JetBrainsMono Nerd Font Mono"
font_size        16.0
italic_font      auto


# === layouts === 
enabled_layouts                     tall,horizontal,vertical,stack
#   toggle full "terminal"
unmap ctrl+shift+f
map ctrl+shift+f toggle_layout stack


# === tabs === 
tab_bar_edge                        top
tab_bar_style                       slant
tab_bar_min_tabs                    1
#   new tab with rename
unmap cmd+t
map cmd+t combine : new_tab : set_tab_title " "
#   rename tab (with clearing current name) 
unmap cmd+shift+i
map cmd+shift+i combine : set_tab_title " " : set_tab_title
#   focus
unmap ctrl+]
unmap ctrl+[
map ctrl+] next_tab
map ctrl+[ previous_tab


# === terminal and shell ===
macos_option_as_alt                 yes
macos_quit_when_last_window_closed  yes
macos_show_window_title             no
allow_remote_control                no
confirm_os_window_close             0
enable_audio_bell                   no
hide_window_decorations             yes
shell_integration                   no_title


# === windows ===
window_padding_width                4
#   new window
unmap cmd+enter
map cmd+enter new_window_with_cwd
#   focus
unmap ctrl+left
unmap ctrl+right
unmap ctrl+up
unmap ctrl+down
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down
#  move
unmap ctrl+shift+left
unmap ctrl+shift+right
unmap ctrl+shift+up
unmap ctrl+shift+down
map ctrl+shift+left move_window left
map ctrl+shift+right move_window right
map ctrl+shift+up move_window up
map ctrl+shift+down move_window down


# tinted theme sets the values in this file to selected theme
include ./tinted-theming.conf
