###################################################################
# https://docs.helix-editor.com/master/commands.html
###################################################################
theme = "onedark"

[editor]
auto-pairs = false                                  # do not auto pair symbols
auto-save = true
bufferline = "always"                               # show buffer tabs at all times
color-modes = true                                  # color status line MODE indicator (it's pretty)
cursorline = true                                   # highlight all rows with cursor
jump-label-alphabet = "asdfjkl;ghxcvbnmqweruioptyz" #home row outward
line-number = "absolute"                            # relative absolute
mouse = true
shell = ["zsh", "-c"]
smart-tab.enable = false
soft-wrap.enable = true
# diagnostics after v2.25 
end-of-line-diagnostics = "hint"
inline-diagnostics.cursor-line = "error"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = true
git-global = true
# max-depth  = 4

[editor.indent-guides]
render = true
character = "|"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "file-modification-indicator",
  "version-control",
]
center = ["position", "selections"]
right = ["diagnostics", "file-encoding", "file-line-ending", "file-type"]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

###################################################################
# key maps
###################################################################

[keys.normal]
"$" = "goto_line_end" # vim like 
"," = "goto_word" # also 'gw', open the 2char jump list
"0" = "goto_line_start" # vim like 
"G" = "goto_file_end" # vim like 
"H" = "goto_line_start"
"L" = "goto_line_end"
"V" = ["select_mode", "extend_to_line_bounds"] # vim like  
"^" = "goto_first_nonwhitespace" # vim like 
"`" = "switch_case" # vim like 
"y" = [
  "yank_main_selection_to_clipboard",
  "yank",
] # vim like yank + yank to clipboard
"~" = "switch_case" # vim like 
esc = ["collapse_selection", "keep_primary_selection", ":write"] # vim like 
# "&" = ["split_selection_on_newline","align_selections"]

[keys.normal.space]
q = ":write-quit-all"
"/" = ":pipe sort"    # expected sort. ":sort" is different

# (e)ditor
[keys.normal."'"]
c = ":config-open"
l = ":open ~/.config/helix/languages.toml"
r = ":config-reload"
"." = ":open ~/Source/github.com/jeffwindsor/dotfiles"
"," = ":open ~/Source/github.com/jeffwindsor/dotfiles/.shellrc"
d = ":open ~/Source/github.com/jeffwindsor/nix-darwin-config/flake.nix"
e = ":open ~/Documents/personal/exocortex"
g = ":open ~/Source/github.com/jeffwindsor/gnome-config"
j = ":open ~/Source/github.com/jeffwindsor"
n = ":open ~/Source/github.com/jeffwindsor/nixos-config"
s = ":open ~/Source/github.com/jeffwindsor/startpage/index.html"
v = ":open ~/Source/github.com/jeffwindsor/nvim-config"

# tools(.)
# [keys.normal.space."."]
# f = [":new", ":insert-output lf", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!"]
# d = [":new", ":insert-output lazydocker", ":buffer-close!", ":redraw"]     # lazygit    
# g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]     # lazygit    
# y = [":new", ":insert-output yazi", ":buffer-close!", ":redraw"]     # yazi

# (t)hemes  
[keys.normal.t]
a = ":theme autumn_night"
b = ":theme base16_transparent"
c = ":theme catppuccin_frappe"
d = ":theme default"
e = ":theme ayu_evolve"
g = ":theme gruvbox"
i = ":theme iceberg-dark"
j = ":theme jellybeans"
k = ":theme kanagawa"
l = ":theme ayu_light"
m = ":theme molokai"
n = ":theme nord"
o = ":theme onedark"
p = ":theme papercolor-dark"
s = ":theme sonokai"
t = ":theme tokyonight_storm"
z = ":theme zed_onedark"


[keys.insert]
esc = ["collapse_selection", "normal_mode", ":write"] # vim like escape


[keys.select]
# mimic the normal keymap adds
"$" = "goto_line_end"
"," = "goto_word"
"0" = "goto_line_start"
"G" = "goto_file_end"
"H" = "goto_line_start"
"L" = "goto_line_end"
"V" = ["select_mode", "extend_to_line_bounds"]
"^" = "goto_first_nonwhitespace"
"`" = "switch_case"
"y" = ["yank_main_selection_to_clipboard", "yank"]
"~" = "switch_case"
esc = ["collapse_selection", "normal_mode", ":write"]
