###################################################################
# https://docs.helix-editor.com/master/commands.html
###################################################################

theme = "kanagawa"

[editor]
auto-save   = true
bufferline  = "always"
color-modes = true
line-number = "relative"  #"relative" #"absolute"
mouse       = true
shell       = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden     = false
git-ignore = true
git-global = true

[editor.indent-guides]
render    = true
character = "|"

[editor.statusline]
left   = [ "mode","spinner","file-name","file-modification-indicator","version-control" ]
center = [ "position","selections" ]
right  = [ "diagnostics","file-encoding","file-line-ending","file-type"]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

###################################################################
# key maps
# , = switch buffer
# z = Zen Mode
###################################################################

[keys.normal]
# Switch case of the selected text
"H" = "goto_line_start"
"L" = "goto_line_end"

# VIM LIKE (CAUSE IT MAKES IT EASIER TO SWITCH)
esc = ["collapse_selection","keep_primary_selection",":write"] # vim like esc 
"$" = "goto_line_end"
"0" = "goto_line_start"
"G" = "goto_file_end"
"V" = ["select_mode", "extend_to_line_bounds"] 
"^" = "goto_first_nonwhitespace"
"`" = "switch_case"
"x" = "delete_selection"
"y" = ["yank_main_selection_to_clipboard","yank"] # vim like yank + yank to clipboard
"~" = "switch_case"

[keys.normal.space]
q = ":write-quit-all"

# lazy git
#g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

# themes  
[keys.normal.space.t]
b = ":theme base16_terminal"
d = ":theme default"
g = ":theme github_dark_high_contrast"
k = ":theme kanagawa"
m = ":theme molokai"
n = ":theme nord"
s = ":theme sonokai" 
t = ":theme tokyonight_storm"

[keys.insert]
esc = ["collapse_selection", "normal_mode", ":write"]

[keys.select]
"H" = "goto_line_start"
"L" = "goto_line_end"

# VIM LIKE (CAUSE IT MAKES IT EASIER TO SWITCH)
esc = ["collapse_selection","keep_primary_selection",":write"] # vim like esc 
"$" = "goto_line_end"
"0" = "goto_line_start"
"G" = "goto_file_end"
"V" = ["select_mode", "extend_to_line_bounds"] 
"^" = "goto_first_nonwhitespace"
"`" = "switch_case"
"x" = "delete_selection"
"y" = ["yank_main_selection_to_clipboard","yank"] # vim like yank + yank to clipboard
"~" = "switch_case"
