###################################################################
# https://docs.helix-editor.com/master/commands.html
###################################################################

theme = "kanagawa"

[editor]
auto-save   = true
bufferline  = "always"
color-modes = true
line-number = "relative"  #"relative" #"absolute"
mouse       = true
shell       = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden     = false
git-ignore = true
git-global = true

[editor.indent-guides]
render    = true
character = "|"

[editor.statusline]
left   = [ "mode","spinner","file-name","file-modification-indicator","version-control" ]
center = [ "position","selections" ]
right  = [ "diagnostics","file-encoding","file-line-ending","file-type"]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

###################################################################
# key maps
# , = switch buffer
# z = Zen Mode
###################################################################

[keys.normal]
# Switch case of the selected text
"`" = "switch_case"
"~" = "switch_case"
"H" = "goto_line_start"
"L" = "goto_line_end"
"G" = "goto_file_end"

# vim like yank + yank to clipboard
y = ["yank_main_selection_to_clipboard","yank"]

# vim like esc 
esc = ["collapse_selection","keep_primary_selection",":write"]

[keys.normal.space]
q = ":write-quit-all"
# lazy git
#g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

#[keys.normal.space.b]
#c = ":buffer-close"
#"." = ":buffer-next"
#"," = ":buffer-previous"
#n = ":new"

# themes  
[keys.normal.space.t]
b = ":theme base16_terminal"
d = ":theme default"
g = ":theme github_dark_high_contrast"
k = ":theme kanagawa"
m = ":theme molokai"
n = ":theme nord"
s = ":theme sonokai" 
t = ":theme tokyonight_storm"

[keys.insert]
esc = ["collapse_selection", "normal_mode", ":write"]

[keys.select]
# auto save on returning to normal mode
esc = ["collapse_selection","normal_mode",":write"] 
"H" = "goto_line_start"
"L" = "goto_line_end"
"G" = "goto_file_end"
          
# Switch case of the selected text
 "`" = "switch_case"
 "~" = "switch_case"
# vim like yank + yank to clipboard
y = ["yank_main_selection_to_clipboard","yank"]
