###################################################################
# https://docs.helix-editor.com/master/commands.html
###################################################################

theme = "papercolor-dark"

[editor]
auto-save   = true
bufferline  = "always"
color-modes = true
cursorline  = true
end-of-line-diagnostics = "hint"
jump-label-alphabet = "asdfjkl;ghxcvbnmqweruioptyz"  #home row outward
line-number = "absolute"  # relative absolute
mouse       = true
shell       = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden     = false
git-ignore = true
git-global = true
# max-depth  = 4

[editor.indent-guides]
render    = true
character = "|"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.soft-wrap]
enable = true

[editor.smart-tab]
enable = false

[editor.statusline]
left   = [ "mode","spinner","file-name","file-modification-indicator","version-control" ]
center = [ "position","selections" ]
right  = [ "diagnostics","file-encoding","file-line-ending","file-type"]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

###################################################################
# key maps
###################################################################

[keys.normal]
"," = "goto_word"   # also 'gw', open the 2char jump list
"H" = "goto_line_start"
"L" = "goto_line_end"

# VIM LIKE (CAUSE IT MAKES IT EASIER TO SWITCH)
esc = ["collapse_selection","keep_primary_selection",":write"] # vim like esc 
"$" = "goto_line_end"
"0" = "goto_line_start"
"G" = "goto_file_end"
"V" = ["select_mode", "extend_to_line_bounds"] 
"^" = "goto_first_nonwhitespace"
"`" = "switch_case"
"y" = ["yank_main_selection_to_clipboard","yank"] # vim like yank + yank to clipboard
"~" = "switch_case"

[keys.normal.space]
# lazy git
#g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
q = ":write-quit-all"

# (e)ditor
[keys.normal.space.e]
d = ":open ~/Source/github.com/jeffwindsor/dotfiles"
g = ":open ~/Source/github.com/jeffwindsor/gnome-config"
h = ":config-open"
j = ":open ~/Source/github.com/jeffwindsor"
l = ":open ~/.config/helix/languages.toml"
N = ":open ~/Source/github.com/jeffwindsor/nixos-config"
n = ":open ~/Source/github.com/jeffwindsor/nvim-config"
r = ":config-reload"

# (t)hemes  
[keys.normal.space.t]
a = ":theme autumn_night"
b = ":theme base16_transparent"
c = ":theme catppuccin_frappe"
d = ":theme default"
e = ":theme ayu_evolve"
g = ":theme gruvbox"
i = ":theme iceberg-dark"
j = ":theme jellybeans"
k = ":theme kanagawa"
l = ":theme ayu_light"
m = ":theme molokai"
n = ":theme nord"
o = ":theme onedark"
p = ":theme papercolor-dark"
s = ":theme sonokai" 
t = ":theme tokyonight_storm"
z = ":theme zed_onedark"




[keys.insert]
esc = ["collapse_selection", "normal_mode", ":write"]

[keys.select]
"H" = "goto_line_start"
"L" = "goto_line_end"

# VIM LIKE (CAUSE IT MAKES IT EASIER TO SWITCH)
esc = ["collapse_selection","normal_mode",":write"] # vim like esc 
"$" = "goto_line_end"
"0" = "goto_line_start"
"G" = "goto_file_end"
"V" = ["select_mode", "extend_to_line_bounds"] 
"^" = "goto_first_nonwhitespace"
"`" = "switch_case"
# "x" = "delete_selection"
"y" = ["yank_main_selection_to_clipboard","yank"] # vim like yank + yank to clipboard
"~" = "switch_case"
