#== BASH ==
[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 4, unit = " " }

[language.formatter]
command = "shfmt"

#== NIX ==
[[language]]
name = "nix"
language-servers = ["nixd", "nil"]

[language-server.nixd]
command = "nixd"

#== PYTHON ==
[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = " " }

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

#== HASKELL ==
[[language]]
name = "haskell"

[language.formatter]
command = "hindent"
args = ["-"]

#== TOML ==
[[language]]
name = "toml"
auto-format = true
comment-token = "#"
language-servers = ["taplo"]

[language.formatter]
command = "taplo"
args = ["fmt", "-"]

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

[language-server.taplo.config]
# Workaround for nonsense of being nonfunctional outside git directories
# (https://github.com/helix-editor/helix/issues/3897#issuecomment-2361674437)
root_dir = [".git", "*.toml"]
