#== BASH ==
[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 4, unit = " " }

[language.formatter]
command = "shfmt"

#== NIX ==
[[language]]
name = "nix"
language-servers = ["nixd", "nil"]

[language-server.nixd]
command = "nixd"

#== PYTHON ==
[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = " " }

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

#== TOML ==
[[language]]
name = "toml"
auto-format = true
# indent = { tab-width = 4, unit = " " }

[language.formatter]
command = "taplo"
args = ["format", "-"]
