[[language]]
name="python"
auto-format = true
indent = { tab-width = 4, unit = " " }

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

[[language]]
name="bash"
auto-format = true
indent = { tab-width = 4, unit = " " }

[language.formatter]
command = "shfmt"

# [[language]]
# name = "nix"
# language-servers = ["nixd","nil"]

# [language-server.nixd]
# command = "nixd"
