#!/usr/bin/env bash
# Writes ~/.config/lsd/colors.yaml using Base24 palette env vars.
# This file is NOT stowed — created fresh by tinty on each apply.

set -euo pipefail

DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lsd"
mkdir -p "$DIR"

get_hex() {
  local base="$1" r_def="$2" g_def="$3" b_def="$4"
  local r_var="TINTY_SCHEME_PALETTE_${base}_HEX_R"
  local g_var="TINTY_SCHEME_PALETTE_${base}_HEX_G"
  local b_var="TINTY_SCHEME_PALETTE_${base}_HEX_B"
  echo "${!r_var:-$r_def}${!g_var:-$g_def}${!b_var:-$b_def}"
}

BG="$(get_hex BASE00 28 28 28)"
COMMENT="$(get_hex BASE03 58 58 58)"
FG="$(get_hex BASE05 d8 d8 d8)"
RED="$(get_hex BASE08 ab 46 42)"
ORANGE="$(get_hex BASE09 dc 96 56)"
YELLOW="$(get_hex BASE0A f7 ca 88)"
GREEN="$(get_hex BASE0B a1 b5 6c)"
CYAN="$(get_hex BASE0C 86 c1 b9)"
BLUE="$(get_hex BASE0D 7c af c2)"
PURPLE="$(get_hex BASE0E ba 8b af)"

cat > "$DIR/colors.yaml" <<EOF
# Generated by tinty — do not edit manually
User: "#${FG}"
Group: "#${COMMENT}"

Permission:
  read: "#${YELLOW}"
  write: "#${ORANGE}"
  exec: "#${GREEN}"
  exec-sticky: "#${CYAN}"
  no-access: "#${COMMENT}"
  octal: "#${BLUE}"
  acl: "#${CYAN}"
  context: "#${PURPLE}"

Date:
  hour-old: "#${GREEN}"
  day-old: "#${YELLOW}"
  older: "#${COMMENT}"

Size:
  none: "#${COMMENT}"
  small: "#${FG}"
  medium: "#${YELLOW}"
  large: "#${ORANGE}"

Links:
  valid: "#${PURPLE}"
  invalid: "#${RED}"

INode:
  valid: "#${CYAN}"
  invalid: "#${RED}"

GitStatus:
  default: "#${COMMENT}"
  unmodified: "#${COMMENT}"
  ignored: "#${COMMENT}"
  new-in-index: "#${GREEN}"
  new-in-workdir: "#${YELLOW}"
  typechange: "#${ORANGE}"
  deleted: "#${RED}"
  renamed: "#${YELLOW}"
  modified: "#${YELLOW}"
  staged: "#${GREEN}"
  conflicted: "#${RED}"
EOF
