#!/usr/bin/env bash
# Writes ~/.config/lsd/colors.yaml using Base24 palette env vars.
# This file is NOT stowed — created fresh by tinty on each apply.

set -euo pipefail

DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lsd"
mkdir -p "$DIR"

get_rgb() {
  local base="$1" r_def="$2" g_def="$3" b_def="$4"
  local r_var="TINTY_SCHEME_PALETTE_${base}_HEX_R"
  local g_var="TINTY_SCHEME_PALETTE_${base}_HEX_G"
  local b_var="TINTY_SCHEME_PALETTE_${base}_HEX_B"
  local r_hex="${!r_var:-$r_def}"
  local g_hex="${!g_var:-$g_def}"
  local b_hex="${!b_var:-$b_def}"
  echo "$((16#$r_hex)), $((16#$g_hex)), $((16#$b_hex))"
}

BG="$(get_rgb BASE00 28 28 28)"
COMMENT="$(get_rgb BASE03 58 58 58)"
FG="$(get_rgb BASE05 d8 d8 d8)"
RED="$(get_rgb BASE08 ab 46 42)"
ORANGE="$(get_rgb BASE09 dc 96 56)"
YELLOW="$(get_rgb BASE0A f7 ca 88)"
GREEN="$(get_rgb BASE0B a1 b5 6c)"
CYAN="$(get_rgb BASE0C 86 c1 b9)"
BLUE="$(get_rgb BASE0D 7c af c2)"
PURPLE="$(get_rgb BASE0E ba 8b af)"

cat > "$DIR/colors.yaml" <<EOF
# Generated by tinty — do not edit manually
user: [$FG]
group: [$COMMENT]

permission:
  read: [$YELLOW]
  write: [$ORANGE]
  exec: [$GREEN]
  exec-sticky: [$CYAN]
  no-access: [$COMMENT]
  octal: [$BLUE]
  acl: [$CYAN]
  context: [$PURPLE]

date:
  hour-old: [$GREEN]
  day-old: [$YELLOW]
  older: [$COMMENT]

size:
  none: [$COMMENT]
  small: [$FG]
  medium: [$YELLOW]
  large: [$ORANGE]

links:
  valid: [$PURPLE]
  invalid: [$RED]

inode:
  valid: [$CYAN]
  invalid: [$RED]

git-status:
  default: [$COMMENT]
  unmodified: [$COMMENT]
  ignored: [$COMMENT]
  new-in-index: [$GREEN]
  new-in-workdir: [$YELLOW]
  typechange: [$ORANGE]
  deleted: [$RED]
  renamed: [$YELLOW]
  modified: [$YELLOW]
  conflicted: [$RED]
EOF
