#!/usr/bin/env bash
# Writes ~/.config/yazi/flavors/tinted-scheme.yazi/flavor.toml using Base16 palette env vars.
# This file is NOT stowed — created fresh by tinty on each apply.

set -euo pipefail

DIR="${XDG_CONFIG_HOME:-$HOME/.config}/yazi/flavors/tinted-scheme.yazi"
mkdir -p "$DIR"

get_hex() {
  local base="$1" r_def="$2" g_def="$3" b_def="$4"
  local r_var="TINTY_SCHEME_PALETTE_${base}_HEX_R"
  local g_var="TINTY_SCHEME_PALETTE_${base}_HEX_G"
  local b_var="TINTY_SCHEME_PALETTE_${base}_HEX_B"
  echo "${!r_var:-$r_def}${!g_var:-$g_def}${!b_var:-$b_def}"
}

BASE00="$(get_hex BASE00 28 28 28)"  # bg
BASE01="$(get_hex BASE01 38 38 38)"  # bg highlight
BASE02="$(get_hex BASE02 48 48 48)"  # selection bg
BASE03="$(get_hex BASE03 58 58 58)"  # comments / inactive
BASE04="$(get_hex BASE04 b8 b8 b8)"  # dark fg
BASE05="$(get_hex BASE05 d8 d8 d8)"  # fg
BASE08="$(get_hex BASE08 ab 46 42)"  # red
BASE09="$(get_hex BASE09 dc 96 56)"  # orange
BASE0A="$(get_hex BASE0A f7 ca 88)"  # yellow
BASE0B="$(get_hex BASE0B a1 b5 6c)"  # green
BASE0C="$(get_hex BASE0C 86 c1 b9)"  # cyan
BASE0D="$(get_hex BASE0D 7c af c2)"  # blue
BASE0E="$(get_hex BASE0E ba 8b af)"  # purple

cat > "$DIR/flavor.toml" <<EOF
# Generated by tinty — do not edit manually

[flavor]

[manager]
cwd = { fg = "#${BASE0D}" }

hovered         = { fg = "#${BASE00}", bg = "#${BASE0D}", bold = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#${BASE0A}", bold = true, italic = true, underline = true }
find_position = { fg = "#${BASE09}", bold = true, italic = true }

marker_copied   = { fg = "#${BASE0A}", bg = "#${BASE0A}" }
marker_cut      = { fg = "#${BASE08}", bg = "#${BASE08}" }
marker_marked   = { fg = "#${BASE0E}", bg = "#${BASE0E}" }
marker_selected = { fg = "#${BASE0D}", bg = "#${BASE0D}" }

tab_active   = { fg = "#${BASE05}", bg = "#${BASE02}", bold = true }
tab_inactive = { fg = "#${BASE03}" }
tab_width    = 1

count_copied   = { fg = "#${BASE00}", bg = "#${BASE0A}" }
count_cut      = { fg = "#${BASE00}", bg = "#${BASE08}" }
count_selected = { fg = "#${BASE00}", bg = "#${BASE0D}" }

border_symbol = "│"
border_style  = { fg = "#${BASE0D}" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#${BASE02}", bg = "#${BASE02}" }

mode_normal = { fg = "#${BASE00}", bg = "#${BASE0D}", bold = true }
mode_select = { fg = "#${BASE00}", bg = "#${BASE0B}", bold = true }
mode_unset  = { fg = "#${BASE00}", bg = "#${BASE09}", bold = true }

progress_label  = { bold = true }
progress_normal = { fg = "#${BASE0D}", bg = "#${BASE02}" }
progress_error  = { fg = "#${BASE08}", bg = "#${BASE02}" }

permissions_t = { fg = "#${BASE03}" }
permissions_r = { fg = "#${BASE0A}" }
permissions_w = { fg = "#${BASE08}" }
permissions_x = { fg = "#${BASE0B}" }
permissions_s = { fg = "#${BASE02}" }

[input]
border   = { fg = "#${BASE0D}" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "#${BASE0D}" }
active   = { bg = "#${BASE02}" }
inactive = {}

[tasks]
border  = { fg = "#${BASE0D}" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#${BASE01}" }
cand            = { fg = "#${BASE0D}" }
rest            = { fg = "#${BASE03}" }
desc            = { fg = "#${BASE04}" }
separator       = "  "
separator_style = { fg = "#${BASE03}" }

[help]
on      = { fg = "#${BASE0D}" }
run     = { fg = "#${BASE0C}" }
desc    = { fg = "#${BASE04}" }
hovered = { bg = "#${BASE02}", bold = true }
footer  = { fg = "#${BASE01}", bg = "#${BASE04}" }

[notify]
title_info  = { fg = "#${BASE0D}" }
title_warn  = { fg = "#${BASE0A}" }
title_error = { fg = "#${BASE08}" }

[filetype]
rules = [
  { mime = "image/*",                  fg = "#${BASE0D}" },
  { mime = "video/*",                  fg = "#${BASE0C}" },
  { mime = "audio/*",                  fg = "#${BASE0C}" },
  { mime = "application/zip",          fg = "#${BASE0A}" },
  { mime = "application/gzip",         fg = "#${BASE0A}" },
  { mime = "application/x-tar",        fg = "#${BASE0A}" },
  { mime = "application/x-xz",         fg = "#${BASE0A}" },
  { mime = "application/x-bzip2",      fg = "#${BASE0A}" },
  { mime = "application/x-7z-compressed", fg = "#${BASE0A}" },
  { mime = "application/x-rar",        fg = "#${BASE0A}" },
  { mime = "application/zstd",         fg = "#${BASE0A}" },
  { mime = "application/x-executable", fg = "#${BASE0B}" },
  { mime = "application/x-mach-binary",fg = "#${BASE0B}" },
  { name = "*.toml",  fg = "#${BASE09}" },
  { name = "*.yaml",  fg = "#${BASE09}" },
  { name = "*.yml",   fg = "#${BASE09}" },
  { name = "*.json",  fg = "#${BASE09}" },
  { name = "*.md",    fg = "#${BASE0E}" },
  { name = "*/",      fg = "#${BASE04}" },
  { name = "*",       fg = "#${BASE05}" },
]
EOF
