#!/usr/bin/env zsh

config=$XDG_CONFIG_HOME/alacritty
themes=$HOME/.local/themes/alacritty

if [ -z "$1" ]; then
  # select theme
  selected=$(fd . $themes | fzf)
else
  selected="$themes/$1.yml"
fi  

# merge base os and picked theme to over write alacrity config
cat $config/os.yml "${selected}" > $config/alacritty.yml

